name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: 'Hello World'
    
    steps:
      - name: Print environment variable
        run: echo "The value of MY_VARIABLE is $MY_VARIABLE"
