name: Project
on: push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: printing hello world
      run: |
          echo "hello world"
          echo "hello humans"
          echo "hello aliens"
