name: Job-Level Conditional Execution

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This always runs"
      
      - name: Step 2
        if: github.ref == 'refs/heads/main'
        run: echo "This runs only on pushes to main"
        
      - name: Step 3
        if: github.ref != 'refs/heads/main'
        run: echo "This runs on every push except main"
