name: Example Workflow with Secrets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_API_KEY: ${{ secrets.API_KEY }}
    
    steps:
      - name: Use secret in workflow
        run: echo "Using secret API key: $SECRET_API_KEY"
